name: Jupiter Toys Tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          command: npm run test:qa:cucumber